// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_dbar_c
arma::mat calc_dbar_c(int nday, int ntupq, arma::mat day_idx, arma::mat tupq_idx, arma::mat mat_weights_tau, arma::mat mat_weights_qdatetime, Rcpp::List price_slist, Rcpp::List cf_slist);
RcppExport SEXP _ycevo_calc_dbar_c(SEXP ndaySEXP, SEXP ntupqSEXP, SEXP day_idxSEXP, SEXP tupq_idxSEXP, SEXP mat_weights_tauSEXP, SEXP mat_weights_qdatetimeSEXP, SEXP price_slistSEXP, SEXP cf_slistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nday(ndaySEXP);
    Rcpp::traits::input_parameter< int >::type ntupq(ntupqSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type day_idx(day_idxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type tupq_idx(tupq_idxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mat_weights_tau(mat_weights_tauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mat_weights_qdatetime(mat_weights_qdatetimeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type price_slist(price_slistSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type cf_slist(cf_slistSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_dbar_c(nday, ntupq, day_idx, tupq_idx, mat_weights_tau, mat_weights_qdatetime, price_slist, cf_slist));
    return rcpp_result_gen;
END_RCPP
}
// calc_dbar_c2
arma::mat calc_dbar_c2(int nday, int ntupq, arma::mat day_idx, arma::mat tupq_idx, arma::mat mat_weights_tau, arma::mat mat_weights_qdatetime, Rcpp::List price_slist, Rcpp::List cf_slist);
RcppExport SEXP _ycevo_calc_dbar_c2(SEXP ndaySEXP, SEXP ntupqSEXP, SEXP day_idxSEXP, SEXP tupq_idxSEXP, SEXP mat_weights_tauSEXP, SEXP mat_weights_qdatetimeSEXP, SEXP price_slistSEXP, SEXP cf_slistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nday(ndaySEXP);
    Rcpp::traits::input_parameter< int >::type ntupq(ntupqSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type day_idx(day_idxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type tupq_idx(tupq_idxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mat_weights_tau(mat_weights_tauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mat_weights_qdatetime(mat_weights_qdatetimeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type price_slist(price_slistSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type cf_slist(cf_slistSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_dbar_c2(nday, ntupq, day_idx, tupq_idx, mat_weights_tau, mat_weights_qdatetime, price_slist, cf_slist));
    return rcpp_result_gen;
END_RCPP
}
// calc_dbar_m
arma::sp_mat calc_dbar_m(arma::sp_mat& mat_weights_tau, arma::sp_mat& mat_weights_qdatetime, const arma::sp_mat& price_smat, const arma::sp_mat& cf_smat);
RcppExport SEXP _ycevo_calc_dbar_m(SEXP mat_weights_tauSEXP, SEXP mat_weights_qdatetimeSEXP, SEXP price_smatSEXP, SEXP cf_smatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type mat_weights_tau(mat_weights_tauSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type mat_weights_qdatetime(mat_weights_qdatetimeSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type price_smat(price_smatSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type cf_smat(cf_smatSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_dbar_m(mat_weights_tau, mat_weights_qdatetime, price_smat, cf_smat));
    return rcpp_result_gen;
END_RCPP
}
// calc_dbar_m2
arma::sp_mat calc_dbar_m2(arma::sp_mat& mat_weights_tau, arma::sp_mat& mat_weights_qdatetime, const arma::sp_mat& price_smat, const arma::sp_mat& cf_smat);
RcppExport SEXP _ycevo_calc_dbar_m2(SEXP mat_weights_tauSEXP, SEXP mat_weights_qdatetimeSEXP, SEXP price_smatSEXP, SEXP cf_smatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::sp_mat& >::type mat_weights_tau(mat_weights_tauSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat& >::type mat_weights_qdatetime(mat_weights_qdatetimeSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type price_smat(price_smatSEXP);
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type cf_smat(cf_smatSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_dbar_m2(mat_weights_tau, mat_weights_qdatetime, price_smat, cf_smat));
    return rcpp_result_gen;
END_RCPP
}
// calc_hhat_num2_c
arma::cube calc_hhat_num2_c(int nday, int ntupq_tau, int ntupq_tau_p, arma::mat day_idx, arma::mat tupq_idx_tau, arma::mat tupq_idx_tau_p, arma::mat mat_weights_tau, arma::mat mat_weights_tau_p, arma::mat mat_weights_qdatetime, Rcpp::List cf_slist);
RcppExport SEXP _ycevo_calc_hhat_num2_c(SEXP ndaySEXP, SEXP ntupq_tauSEXP, SEXP ntupq_tau_pSEXP, SEXP day_idxSEXP, SEXP tupq_idx_tauSEXP, SEXP tupq_idx_tau_pSEXP, SEXP mat_weights_tauSEXP, SEXP mat_weights_tau_pSEXP, SEXP mat_weights_qdatetimeSEXP, SEXP cf_slistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nday(ndaySEXP);
    Rcpp::traits::input_parameter< int >::type ntupq_tau(ntupq_tauSEXP);
    Rcpp::traits::input_parameter< int >::type ntupq_tau_p(ntupq_tau_pSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type day_idx(day_idxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type tupq_idx_tau(tupq_idx_tauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type tupq_idx_tau_p(tupq_idx_tau_pSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mat_weights_tau(mat_weights_tauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mat_weights_tau_p(mat_weights_tau_pSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mat_weights_qdatetime(mat_weights_qdatetimeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type cf_slist(cf_slistSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_hhat_num2_c(nday, ntupq_tau, ntupq_tau_p, day_idx, tupq_idx_tau, tupq_idx_tau_p, mat_weights_tau, mat_weights_tau_p, mat_weights_qdatetime, cf_slist));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ycevo_calc_dbar_c", (DL_FUNC) &_ycevo_calc_dbar_c, 8},
    {"_ycevo_calc_dbar_c2", (DL_FUNC) &_ycevo_calc_dbar_c2, 8},
    {"_ycevo_calc_dbar_m", (DL_FUNC) &_ycevo_calc_dbar_m, 4},
    {"_ycevo_calc_dbar_m2", (DL_FUNC) &_ycevo_calc_dbar_m2, 4},
    {"_ycevo_calc_hhat_num2_c", (DL_FUNC) &_ycevo_calc_hhat_num2_c, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_ycevo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
