// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_dbar_c
arma::mat calc_dbar_c(int ntupq, arma::mat day_idx, arma::mat tupq_idx, arma::mat mat_weights_tau, arma::mat mat_weights_qdatetime, Rcpp::List price_slist, Rcpp::List cf_slist);
RcppExport SEXP _ycevo_calc_dbar_c(SEXP ntupqSEXP, SEXP day_idxSEXP, SEXP tupq_idxSEXP, SEXP mat_weights_tauSEXP, SEXP mat_weights_qdatetimeSEXP, SEXP price_slistSEXP, SEXP cf_slistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ntupq(ntupqSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type day_idx(day_idxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type tupq_idx(tupq_idxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mat_weights_tau(mat_weights_tauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mat_weights_qdatetime(mat_weights_qdatetimeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type price_slist(price_slistSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type cf_slist(cf_slistSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_dbar_c(ntupq, day_idx, tupq_idx, mat_weights_tau, mat_weights_qdatetime, price_slist, cf_slist));
    return rcpp_result_gen;
END_RCPP
}
// calc_hhat_num_c
arma::mat calc_hhat_num_c(int ntupq_tau, int ntupq_tau_p, arma::mat day_idx, arma::mat tupq_idx_tau, arma::mat tupq_idx_tau_p, arma::mat mat_weights_tau, arma::mat mat_weights_tau_p, arma::mat mat_weights_qdatetime, Rcpp::List cf_slist, bool same_tau);
RcppExport SEXP _ycevo_calc_hhat_num_c(SEXP ntupq_tauSEXP, SEXP ntupq_tau_pSEXP, SEXP day_idxSEXP, SEXP tupq_idx_tauSEXP, SEXP tupq_idx_tau_pSEXP, SEXP mat_weights_tauSEXP, SEXP mat_weights_tau_pSEXP, SEXP mat_weights_qdatetimeSEXP, SEXP cf_slistSEXP, SEXP same_tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type ntupq_tau(ntupq_tauSEXP);
    Rcpp::traits::input_parameter< int >::type ntupq_tau_p(ntupq_tau_pSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type day_idx(day_idxSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type tupq_idx_tau(tupq_idx_tauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type tupq_idx_tau_p(tupq_idx_tau_pSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mat_weights_tau(mat_weights_tauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mat_weights_tau_p(mat_weights_tau_pSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mat_weights_qdatetime(mat_weights_qdatetimeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type cf_slist(cf_slistSEXP);
    Rcpp::traits::input_parameter< bool >::type same_tau(same_tauSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_hhat_num_c(ntupq_tau, ntupq_tau_p, day_idx, tupq_idx_tau, tupq_idx_tau_p, mat_weights_tau, mat_weights_tau_p, mat_weights_qdatetime, cf_slist, same_tau));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ycevo_calc_dbar_c", (DL_FUNC) &_ycevo_calc_dbar_c, 7},
    {"_ycevo_calc_hhat_num_c", (DL_FUNC) &_ycevo_calc_hhat_num_c, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_ycevo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
