# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_dbar_c <- function(nday, ntupq, day_idx, tupq_idx, ux_window, uu_window, price_slist, cf_slist) {
    .Call('_ycevo_calc_dbar_c', PACKAGE = 'ycevo', nday, ntupq, day_idx, tupq_idx, ux_window, uu_window, price_slist, cf_slist)
}

calc_hhat_num2_c <- function(nday, ntupq_x, ntupq_q, day_idx, tupq_idx_x, tupq_idx_q, ux_window, uq_window, uu_window, cf_slist) {
    .Call('_ycevo_calc_hhat_num2_c', PACKAGE = 'ycevo', nday, ntupq_x, ntupq_q, day_idx, tupq_idx_x, tupq_idx_q, ux_window, uq_window, uu_window, cf_slist)
}

